#write a programme to a logo
print("---------------------------------------------------------------------------------------")
print("|                      -----------------------------                                  |")
print("|                                     ||                                              |")
print("|                                     ||                                              |")
print("|                                     ||                                              |")
print("|                                     ||                                              |")
print("|                                     ||                                              |")
print("|                                     ||                                              |")
print("|                                     ||                                              |")
print("|                                     ||                                              |")
print("|                                     ||                                              |")
print("|                                     ||                                              |")
print("|                                     ||______                                        |")
print("|                                     | ______|                                       |")
print("                                                                                      |")
print("                                                                                      |")
print("                                                                                      |")
print("                                                                                      |")
print("                                                                                      |")